version: '3'
services:
  api:
    build: .
    image: bibhor/gs-spring-boot
    volumes:
      - .:/src
    ports:
      - "8080:8080"
    links:
      - mysql
  mysql:
    image: mysql:5.6
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "password"
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql_row_binlog.cnf:/etc/mysql/conf.d/mysql_row_binlog.cnf
      - ./data/mysql:/var/lib/mysql
  # zookeeper:
  #   image: wurstmeister/zookeeper
  #   ports:
  #     - "2181:2181"
  # kafka:
  #     image: wurstmeister/kafka
  #     ports:
  #       - "9092"
  #     environment:
  #       KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
  #       KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #     volumes:
  #       - /var/run/docker.sock:/var/run/docker.sock
